// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI (migrate, status, diff) must use the Session pooler — it hangs
    // on the Transaction pooler that the running app uses (DATABASE_URL).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
